# ANSI colors can be found at https://github.com/morhetz/gruvbox
[style.description]
underline = false
bold = false
italic = false

[style.command_name]
# foreground = { ansi = 106 }
foreground = { rgb = { r = 1, g = 4, b = 9 } }
underline = false
bold = false
italic = false

[style.example_text]
# background = { ansi = 172 }
# foreground = { ansi = 235 }
background = { rgb = { r = 3, g = 73, b = 180 } }
foreground = { rgb = { r = 255, g = 255, b = 255 } }
underline = false
bold = true
italic = false

[style.example_code]
# foreground = { ansi = 106 }
foreground = { rgb = { r = 3, g = 73, b = 180 } }
underline = false
bold = false
italic = false

[style.example_variable]
# foreground = { ansi = 223 }
foreground = { rgb = { r = 98, g = 44, b = 188 } }
underline = false
bold = false
italic = false

[display]
compact = false
use_pager = false

[updates]
auto_update = true
auto_update_interval_hours = 720

[directories]
