"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# https://yazi-rs.github.io/docs/tips#dropping-to-shell
[[mgr.prepend_keymap]]
on   = [ "<C-s>" ]
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[mgr.prepend_keymap]]
on = [ "g", "a" ]
run = "cd ~/archive"
desc = "Go to archives"

[[mgr.prepend_keymap]]
on = [ "g", "1" ]
run = "cd ~/archive/archive-perso-administrative-docs/le_citadin-e42/lmnp/2023-09-locataire-qi_fang/quittances_loyers/"
desc = "Go Le Citadin"

[[mgr.prepend_keymap]]
on = [ "g", "2" ]
run = "cd ~/archive/archive-perso-administrative-docs/saint_antoine/e105/lmnp/2022-locataire-lijuan_zhu/quittances_loyers/"
desc = "Go Saint-Antoine"

[[mgr.prepend_keymap]]
on = [ "g", "3" ]
run = "cd ~/archive/archive-perso-administrative-docs/jardin_anais/l26/lmnp/2025-lebrave_lapeyre/quittances_loyers/"
desc = "Go Les Jardins d'Anais"

[[mgr.prepend_keymap]]
on = ["<C-g>" ]
run = "plugin fzf"
desc = "Jump to a file/directory via fzf"
